-- ⚠️  OBSOLÈTE — NE PAS EXÉCUTER ⚠️
-- ----------------------------------------------------------------------------
-- Ce script accordait à anon un accès complet (lecture/écriture/suppression) à
-- toutes les tables, y compris les données clients. Il ouvrait une fuite de
-- données et a été REMPLACÉ par le modèle sécurisé de `supabase_schema.sql`.
--
-- Désormais :
--   * anon n'a que la lecture du catalogue public + l'insertion des soumissions ;
--   * le dashboard lit/écrit les données sensibles via les Netlify Functions
--     (admin-api) avec la clé service_role, derrière une session admin signée.
--
-- Pour (ré)appliquer la configuration, exécute UNIQUEMENT `supabase_schema.sql`.
-- Le contenu d'ouverture des droits a été retiré volontairement.
